package com.abyxcz.buildlogic

import kotlin.test.Test
import kotlin.test.assertEquals

class KotlinCodegenTest {

    @Test
    fun `generates external funs for scalars`() {
        val model = CHeaderParser.parse(
            """
            int add_numbers(int a, int b);
            void reset();
            """.trimIndent()
        )
        val out = KotlinCodegen.generate(model, CodegenConfig())

        assertEquals(
            """
            // Generated by CBindingKMP — do not edit.
            package com.abyxcz.cbindingkmp.shared.generated

            internal external fun add_numbersJNI(a: Int, b: Int): Int
            internal external fun resetJNI(): Unit
            """.trimIndent() + "\n",
            out
        )
    }

    @Test
    fun `generates handle, buffer and array signatures with overloads`() {
        val model = CHeaderParser.parse(
            """
            typedef struct bd_ctx bd_ctx;
            bd_ctx* bd_create(const uint8_t* model_bytes, int32_t model_len);
            int32_t bd_detect(bd_ctx* ctx, const uint8_t* pixels, float* out, int32_t max_out);
            void bd_destroy(bd_ctx* ctx);
            """.trimIndent()
        )
        val out = KotlinCodegen.generate(model, CodegenConfig())

        assertEquals(
            """
            // Generated by CBindingKMP — do not edit.
            package com.abyxcz.cbindingkmp.shared.generated

            internal external fun bd_createJNI(model_bytes: java.nio.ByteBuffer, model_len: Int): Long
            internal external fun bd_createArrJNI(model_bytes: ByteArray, model_len: Int): Long
            internal external fun bd_detectJNI(ctx: Long, pixels: java.nio.ByteBuffer, out: FloatArray, max_out: Int): Int
            internal external fun bd_detectArrJNI(ctx: Long, pixels: ByteArray, out: FloatArray, max_out: Int): Int
            internal external fun bd_destroyJNI(ctx: Long): Unit
            """.trimIndent() + "\n",
            out
        )
    }

    @Test
    fun `string functions get a raw UTF-8 external and a String wrapper`() {
        val model = CHeaderParser.parse(
            """
            typedef struct lm_ctx lm_ctx;
            int32_t utf8_length(const char* text);
            int32_t lm_next_token(lm_ctx* ctx, char* out, int32_t cap);
            int32_t greet(const char* name, char* out, int32_t capacity);
            """.trimIndent()
        )
        val out = KotlinCodegen.generate(model, CodegenConfig())

        assertEquals(
            """
            // Generated by CBindingKMP — do not edit.
            package com.abyxcz.cbindingkmp.shared.generated

            internal external fun utf8_lengthUtf8JNI(text: ByteArray): Int
            internal fun utf8_lengthJNI(text: String): Int {
                val textUtf8 = text.cbindingUtf8z()
                return utf8_lengthUtf8JNI(textUtf8)
            }
            internal external fun lm_next_tokenUtf8JNI(ctx: Long, out: ByteArray, cap: Int): Int
            internal fun lm_next_tokenJNI(ctx: Long, capacity: Int = 256): String {
                require(capacity > 0) { "lm_next_token: capacity must be positive, was ${'$'}capacity" }
                var cbindingBuf = ByteArray(capacity)
                var cbindingN = lm_next_tokenUtf8JNI(ctx, cbindingBuf, cbindingBuf.size)
                if (cbindingN < 0) {
                    // Too small: -n is the capacity the C side needs. It must not have consumed state.
                    cbindingBuf = ByteArray(-cbindingN)
                    cbindingN = lm_next_tokenUtf8JNI(ctx, cbindingBuf, cbindingBuf.size)
                }
                check(cbindingN in 0..cbindingBuf.size) {
                    "lm_next_token: returned ${'$'}cbindingN for a ${'$'}{cbindingBuf.size}-byte buffer"
                }
                return cbindingBuf.decodeToString(0, cbindingN)
            }
            internal external fun greetUtf8JNI(name: ByteArray, out: ByteArray, capacity: Int): Int
            internal fun greetJNI(name: String, capacity_: Int = 256): String {
                val nameUtf8 = name.cbindingUtf8z()
                require(capacity_ > 0) { "greet: capacity must be positive, was ${'$'}capacity_" }
                var cbindingBuf = ByteArray(capacity_)
                var cbindingN = greetUtf8JNI(nameUtf8, cbindingBuf, cbindingBuf.size)
                if (cbindingN < 0) {
                    // Too small: -n is the capacity the C side needs. It must not have consumed state.
                    cbindingBuf = ByteArray(-cbindingN)
                    cbindingN = greetUtf8JNI(nameUtf8, cbindingBuf, cbindingBuf.size)
                }
                check(cbindingN in 0..cbindingBuf.size) {
                    "greet: returned ${'$'}cbindingN for a ${'$'}{cbindingBuf.size}-byte buffer"
                }
                return cbindingBuf.decodeToString(0, cbindingN)
            }

            /** NUL-terminated UTF-8 for a `const char*` parameter. */
            private fun String.cbindingUtf8z(): ByteArray {
                val bytes = encodeToByteArray()
                return bytes.copyOf(bytes.size + 1)
            }
            """.trimIndent() + "\n",
            out
        )
    }

    @Test
    fun `files without strings are unchanged`() {
        val out = KotlinCodegen.generate(CHeaderParser.parse("int add_numbers(int a, int b);"), CodegenConfig())
        kotlin.test.assertFalse(out.contains("cbindingUtf8z"), out)
    }
}
