package com.abyxcz.buildlogic

import kotlin.test.Test
import kotlin.test.assertEquals

class KotlinCodegenTest {

    @Test
    fun `generates external funs with configured package`() {
        val model = CHeaderParser.parse(
            """
            int add_numbers(int a, int b);
            void reset();
            """.trimIndent()
        )
        val out = KotlinCodegen.generate(model, CodegenConfig())

        assertEquals(
            """
            // Generated by CBindingKMP — do not edit.
            package com.abyxcz.cbindingkmp.shared.generated

            internal external fun add_numbersJNI(a: Int, b: Int): Int
            internal external fun resetJNI(): Unit
            """.trimIndent() + "\n",
            out
        )
    }
}
