package com.abyxcz.buildlogic

import kotlin.test.Test
import kotlin.test.assertEquals

class KotlinCodegenTest {

    @Test
    fun `generates external funs for scalars`() {
        val model = CHeaderParser.parse(
            """
            int add_numbers(int a, int b);
            void reset();
            """.trimIndent()
        )
        val out = KotlinCodegen.generate(model, CodegenConfig())

        assertEquals(
            """
            // Generated by CBindingKMP — do not edit.
            package com.abyxcz.cbindingkmp.shared.generated

            internal external fun add_numbersJNI(a: Int, b: Int): Int
            internal external fun resetJNI(): Unit
            """.trimIndent() + "\n",
            out
        )
    }

    @Test
    fun `generates handle, buffer and array signatures with overloads`() {
        val model = CHeaderParser.parse(
            """
            typedef struct bd_ctx bd_ctx;
            bd_ctx* bd_create(const uint8_t* model_bytes, int32_t model_len);
            int32_t bd_detect(bd_ctx* ctx, const uint8_t* pixels, float* out, int32_t max_out);
            void bd_destroy(bd_ctx* ctx);
            """.trimIndent()
        )
        val out = KotlinCodegen.generate(model, CodegenConfig())

        assertEquals(
            """
            // Generated by CBindingKMP — do not edit.
            package com.abyxcz.cbindingkmp.shared.generated

            internal external fun bd_createJNI(model_bytes: java.nio.ByteBuffer, model_len: Int): Long
            internal external fun bd_createArrJNI(model_bytes: ByteArray, model_len: Int): Long
            internal external fun bd_detectJNI(ctx: Long, pixels: java.nio.ByteBuffer, out: FloatArray, max_out: Int): Int
            internal external fun bd_detectArrJNI(ctx: Long, pixels: ByteArray, out: FloatArray, max_out: Int): Int
            internal external fun bd_destroyJNI(ctx: Long): Unit
            """.trimIndent() + "\n",
            out
        )
    }
}
