package com.abyxcz.buildlogic

/**
 * Generates the JNI bridge C file. Pure (no Gradle types).
 *
 * Marshalling rules:
 * - Opaque handles (`X*`) cross as `jlong` (cast via `intptr_t`).
 * - `const uint8_t*` (large input buffers, e.g. pixels/model bytes): primary variant
 *   takes a DIRECT ByteBuffer (`GetDirectBufferAddress`, throws IllegalArgumentException
 *   on non-direct); an `...Arr` overload takes `jbyteArray` via GetPrimitiveArrayCritical.
 * - Mutable primitive pointers (`float*`, `int32_t*`, `uint8_t*`): primitive arrays via
 *   GetPrimitiveArrayCritical / Release(0). Const variants release with JNI_ABORT.
 *   Critical sections contain ONLY the native call — callers must keep long-running
 *   calls on direct ByteBuffers, arrays are for small in/out parameters.
 *
 * JNI symbol naming (JNI spec 2.2): package dots become `_`; underscores inside
 * identifiers are escaped `_1`. Wrong escaping fails only at runtime
 * (UnsatisfiedLinkError), which was the original generator's launch-blocking bug.
 */
object JniCodegen {

    /** Escape one Java identifier segment for use inside a JNI symbol. */
    fun jniEscape(segment: String): String = segment.replace("_", "_1")

    /** Full JNI symbol for a top-level Kotlin external function. */
    fun symbolFor(config: CodegenConfig, kotlinFunName: String): String {
        val packagePart = config.jniPackage.split('.').joinToString("_") { jniEscape(it) }
        return "Java_${packagePart}_${jniEscape(config.jniClassName)}_${jniEscape(kotlinFunName)}"
    }

    fun generate(model: CHeaderModel, config: CodegenConfig): String {
        val sb = StringBuilder()
        sb.append("/* Generated by CBindingKMP — do not edit. */\n")
        sb.append("#include <jni.h>\n")
        sb.append("#include <stdint.h>\n")
        config.includeHeaders.forEach { sb.append("#include \"$it\"\n") }
        sb.append("\n")

        model.functions.forEach { func ->
            appendVariant(sb, func, config, byteBufferVariant = true)
            if (func.params.any { it.type.isConstByteBuffer() }) {
                appendVariant(sb, func, config, byteBufferVariant = false)
            }
        }

        return sb.toString()
    }

    private fun CType.isConstByteBuffer(): Boolean =
        this is CType.Pointer && pointee == "uint8_t" && isConst

    private fun appendVariant(
        sb: StringBuilder,
        func: CFunction,
        config: CodegenConfig,
        byteBufferVariant: Boolean
    ) {
        val kotlinName = func.name + (if (byteBufferVariant) "" else "Arr") + "JNI"
        val jniName = symbolFor(config, kotlinName)

        val jniParams = StringBuilder("JNIEnv *env, jclass clazz")
        val prologue = StringBuilder()
        val epilogue = StringBuilder()
        val callArgs = mutableListOf<String>()
        val defaultReturn = defaultReturnFor(func.returnType)

        func.params.forEach { p ->
            when (val t = p.type) {
                is CType.Scalar -> {
                    jniParams.append(", ${scalarJniType(t.name)} ${p.name}")
                    callArgs.add(castScalarArg(t.name, p.name))
                }
                is CType.OpaqueHandle -> {
                    jniParams.append(", jlong ${p.name}")
                    val constPrefix = if (t.isConst) "const " else ""
                    callArgs.add("($constPrefix${t.name}*)(intptr_t)${p.name}")
                }
                is CType.Pointer -> {
                    if (t.isConstByteBufferIn(byteBufferVariant)) {
                        // Direct ByteBuffer path: zero-copy, safe for long native calls.
                        jniParams.append(", jobject ${p.name}")
                        prologue.append(
                            "    const uint8_t* ${p.name}_ptr = (const uint8_t*)(*env)->GetDirectBufferAddress(env, ${p.name});\n" +
                                "    if (${p.name}_ptr == NULL) {\n" +
                                "        (*env)->ThrowNew(env, (*env)->FindClass(env, \"java/lang/IllegalArgumentException\"),\n" +
                                "                         \"${p.name} must be a non-null direct ByteBuffer\");\n" +
                                "        return$defaultReturn;\n" +
                                "    }\n"
                        )
                        callArgs.add("${p.name}_ptr")
                    } else {
                        // Primitive array via Critical: native call only inside the section.
                        val (arrJniType, cElemType) = arrayTypesFor(t.pointee)
                        jniParams.append(", $arrJniType ${p.name}")
                        prologue.append(
                            "    $cElemType* ${p.name}_ptr = ($cElemType*)(*env)->GetPrimitiveArrayCritical(env, ${p.name}, NULL);\n" +
                                "    if (${p.name}_ptr == NULL) {\n" +
                                "        return$defaultReturn; /* OutOfMemoryError already thrown */\n" +
                                "    }\n"
                        )
                        val releaseMode = if (t.isConst) "JNI_ABORT" else "0"
                        epilogue.insert(
                            0,
                            "    (*env)->ReleasePrimitiveArrayCritical(env, ${p.name}, ${p.name}_ptr, $releaseMode);\n"
                        )
                        val constPrefix = if (t.isConst) "const " else ""
                        callArgs.add("($constPrefix${t.pointee}*)${p.name}_ptr")
                    }
                }
            }
        }

        val callExpr = "${func.name}(${callArgs.joinToString(", ")})"
        val body = StringBuilder()
        body.append(prologue)
        when (val rt = func.returnType) {
            is CType.Scalar -> {
                if (rt.name == "void") {
                    body.append("    $callExpr;\n")
                    body.append(epilogue)
                } else {
                    body.append("    ${cReturnType(rt)} result = $callExpr;\n")
                    body.append(epilogue)
                    body.append("    return (${scalarJniType(rt.name)})result;\n")
                }
            }
            is CType.OpaqueHandle -> {
                body.append("    ${rt.name}* result = $callExpr;\n")
                body.append(epilogue)
                body.append("    return (jlong)(intptr_t)result;\n")
            }
            is CType.Pointer -> error("unreachable: parser rejects pointer returns")
        }

        sb.append("JNIEXPORT ${jniReturnType(func.returnType)} JNICALL\n")
        sb.append("$jniName($jniParams) {\n")
        sb.append(body)
        sb.append("}\n\n")
    }

    private fun CType.Pointer.isConstByteBufferIn(byteBufferVariant: Boolean): Boolean =
        byteBufferVariant && pointee == "uint8_t" && isConst

    private fun defaultReturnFor(returnType: CType): String = when (returnType) {
        is CType.Scalar -> if (returnType.name == "void") "" else " 0"
        else -> " 0"
    }

    private fun scalarJniType(name: String): String = when (name) {
        "int", "int32_t" -> "jint"
        "int64_t", "size_t" -> "jlong"
        "float" -> "jfloat"
        "double" -> "jdouble"
        "void" -> "void"
        else -> error("Unsupported scalar: $name")
    }

    private fun castScalarArg(name: String, argName: String): String = when (name) {
        "size_t" -> "(size_t)$argName"
        "int64_t" -> "(int64_t)$argName"
        "int32_t" -> "(int32_t)$argName"
        else -> argName
    }

    private fun cReturnType(t: CType.Scalar): String = t.name

    private fun jniReturnType(t: CType): String = when (t) {
        is CType.Scalar -> scalarJniType(t.name)
        is CType.OpaqueHandle -> "jlong"
        is CType.Pointer -> error("unreachable")
    }

    private fun arrayTypesFor(pointee: String): Pair<String, String> = when (pointee) {
        "uint8_t" -> "jbyteArray" to "jbyte"
        "float" -> "jfloatArray" to "jfloat"
        "int32_t" -> "jintArray" to "jint"
        else -> error("Unsupported array pointee: $pointee")
    }
}
