package com.abyxcz.buildlogic

/**
 * Generates the JNI bridge C file. Pure (no Gradle types).
 *
 * JNI symbol naming (JNI spec 2.2): `Java_<pkg>_<class>_<method>` where package dots
 * become `_`, and characters inside each identifier are escaped — most importantly an
 * underscore becomes `_1`. Getting this wrong compiles fine and fails only at runtime
 * with UnsatisfiedLinkError, which is exactly the bug the original generator had for
 * any C function containing an underscore (i.e. most C APIs).
 */
object JniCodegen {

    /** Escape one Java identifier segment for use inside a JNI symbol. */
    fun jniEscape(segment: String): String = segment.replace("_", "_1")

    /** Full JNI symbol for a top-level Kotlin external function. */
    fun symbolFor(config: CodegenConfig, kotlinFunName: String): String {
        val packagePart = config.jniPackage.split('.').joinToString("_") { jniEscape(it) }
        return "Java_${packagePart}_${jniEscape(config.jniClassName)}_${jniEscape(kotlinFunName)}"
    }

    fun generate(model: CHeaderModel, config: CodegenConfig): String {
        val sb = StringBuilder()
        sb.append("/* Generated by CBindingKMP — do not edit. */\n")
        sb.append("#include <jni.h>\n")
        config.includeHeaders.forEach { sb.append("#include \"$it\"\n") }
        sb.append("\n")

        model.functions.forEach { func ->
            val kotlinName = func.name + "JNI"
            val jniName = symbolFor(config, kotlinName)

            var jniArgs = "JNIEnv *env, jclass clazz"
            val callArgs = mutableListOf<String>()
            func.params.forEach { p ->
                jniArgs += ", ${toJniType(p.type)} ${p.name}"
                callArgs.add(p.name)
            }

            val jniReturnType = toJniType(func.returnType)
            val callExpr = "${func.name}(${callArgs.joinToString(", ")})"

            sb.append("JNIEXPORT $jniReturnType JNICALL\n")
            sb.append("$jniName($jniArgs) {\n")
            if (func.returnType == "void") {
                sb.append("    $callExpr;\n")
            } else {
                sb.append("    return $callExpr;\n")
            }
            sb.append("}\n\n")
        }

        return sb.toString()
    }

    internal fun toJniType(cType: String): String = when (cType) {
        "int" -> "jint"
        "void" -> "void"
        "float" -> "jfloat"
        "double" -> "jdouble"
        else -> error("Unsupported C type for JNI generation: '$cType'")
    }
}
