package com.abyxcz.buildlogic

/**
 * Generates the Kotlin file of `external fun` declarations matching the JNI bridge.
 * Pure (no Gradle types).
 */
object KotlinCodegen {

    fun generate(model: CHeaderModel, config: CodegenConfig): String {
        val sb = StringBuilder()
        sb.append("// Generated by CBindingKMP — do not edit.\n")
        sb.append("package ${config.jniPackage}\n\n")

        model.functions.forEach { func ->
            appendVariant(sb, func, byteBufferVariant = true)
            if (func.params.any { it.type.isConstU8Pointer() }) {
                appendVariant(sb, func, byteBufferVariant = false)
            }
        }

        return sb.toString()
    }

    private fun CType.isConstU8Pointer(): Boolean =
        this is CType.Pointer && pointee == "uint8_t" && isConst

    private fun appendVariant(sb: StringBuilder, func: CFunction, byteBufferVariant: Boolean) {
        val kotlinName = func.name + (if (byteBufferVariant) "" else "Arr") + "JNI"
        val args = func.params.joinToString(", ") { p ->
            "${p.name}: ${kotlinType(p.type, byteBufferVariant)}"
        }
        sb.append("internal external fun $kotlinName($args): ${kotlinReturnType(func.returnType)}\n")
    }

    private fun kotlinType(t: CType, byteBufferVariant: Boolean): String = when (t) {
        is CType.Scalar -> scalarKotlinType(t.name)
        is CType.OpaqueHandle -> "Long"
        is CType.Pointer -> when (t.pointee) {
            "uint8_t" ->
                if (t.isConst && byteBufferVariant) "java.nio.ByteBuffer" else "ByteArray"
            "float" -> "FloatArray"
            "int32_t" -> "IntArray"
            else -> error("Unsupported pointee: ${t.pointee}")
        }
    }

    private fun kotlinReturnType(t: CType): String = when (t) {
        is CType.Scalar -> scalarKotlinType(t.name)
        is CType.OpaqueHandle -> "Long"
        is CType.Pointer -> error("unreachable: parser rejects pointer returns")
    }

    private fun scalarKotlinType(name: String): String = when (name) {
        "int", "int32_t" -> "Int"
        "int64_t", "size_t" -> "Long"
        "float" -> "Float"
        "double" -> "Double"
        "void" -> "Unit"
        else -> error("Unsupported scalar: $name")
    }
}
