package com.abyxcz.buildlogic

/**
 * Generates the Kotlin file of `external fun` declarations matching the JNI bridge.
 * Pure (no Gradle types).
 */
object KotlinCodegen {

    fun generate(model: CHeaderModel, config: CodegenConfig): String {
        val sb = StringBuilder()
        sb.append("// Generated by CBindingKMP — do not edit.\n")
        sb.append("package ${config.jniPackage}\n\n")

        model.functions.forEach { func ->
            val kotlinName = func.name + "JNI"
            val kotlinArgs = func.params.joinToString(", ") { p ->
                "${p.name}: ${toKotlinType(p.type)}"
            }
            val kotlinReturn = toKotlinType(func.returnType)
            sb.append("internal external fun $kotlinName($kotlinArgs): $kotlinReturn\n")
        }

        return sb.toString()
    }

    internal fun toKotlinType(cType: String): String = when (cType) {
        "int" -> "Int"
        "void" -> "Unit"
        "float" -> "Float"
        "double" -> "Double"
        else -> error("Unsupported C type for Kotlin generation: '$cType'")
    }
}
